version: '3.9'
services:
  nginx:
    build:
      context: .
    container_name: ecommerce-api-gateway
    networks:
      - ecommerce-network
    ports:
      - "8080:80" # Maps container port 80 to host port 8080
    volumes:
      - ./html:/usr/share/nginx/html # Bind mount for live edits
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Map host.docker.internal to the host's gateway
  
  node-jwt-validator-service:
    build:
      context: ./node-jwt-validator-service
    container_name: node-jwt-validator-service
    networks:
      - ecommerce-network
    ports:
      - "3000:3000"
    environment:
      - KEYCLOAK_URL=${MICROSERVICE_AUTH_HOST}:${MICROSERVICE_AUTH_PORT}
      - REALM=${MICROSERVICE_AUTH_REALM}

networks:
  ecommerce-network:
    external: true # Connect to the shared network