version: '3.9'
services:
  nginx:
    build:
      context: .
    ports:
      - "8080:80" # Maps container port 80 to host port 8080
    volumes:
      - ./html:/usr/share/nginx/html # Bind mount for live edits
    environment:
      - MICROSERVICE_CART_HOST=${MICROSERVICE_CART_HOST}
      - MICROSERVICE_CART_PORT=${MICROSERVICE_CART_PORT}
      # - MICROSERVICE_USERS_HOST=${MICROSERVICE_USERS_HOST}
      # - MICROSERVICE_USERS_PORT=${MICROSERVICE_USERS_PORT}
      # - MICROSERVICE_PRODUCTS_HOST=${MICROSERVICE_PRODUCTS_HOST}
      # - MICROSERVICE_PRODUCTS_PORT=${MICROSERVICE_PRODUCTS_PORT}
    env_file:
      - .env